/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Leap_WRAP_H_
#define SWIG_Leap_WRAP_H_

class SwigDirector_Listener : public Leap::Listener, public Swig::Director {

public:
    SwigDirector_Listener();
    virtual ~SwigDirector_Listener();
    virtual void onInit(Leap::Controller const &arg0);
    virtual void onConnect(Leap::Controller const &arg0);
    virtual void onDisconnect(Leap::Controller const &arg0);
    virtual void onExit(Leap::Controller const &arg0);
    virtual void onFrame(Leap::Controller const &arg0);
    virtual void onFocusGained(Leap::Controller const &arg0);
    virtual void onFocusLost(Leap::Controller const &arg0);
    virtual void onServiceConnect(Leap::Controller const &arg0);
    virtual void onServiceDisconnect(Leap::Controller const &arg0);
    virtual void onDeviceChange(Leap::Controller const &arg0);
    virtual void onImages(Leap::Controller const &arg0);

    typedef void (* SWIG_Callback0_t)(void *dobj, void *);
    typedef void (* SWIG_Callback1_t)(void *dobj, void *);
    typedef void (* SWIG_Callback2_t)(void *dobj, void *);
    typedef void (* SWIG_Callback3_t)(void *dobj, void *);
    typedef void (* SWIG_Callback4_t)(void *dobj, void *);
    typedef void (* SWIG_Callback5_t)(void *dobj, void *);
    typedef void (* SWIG_Callback6_t)(void *dobj, void *);
    typedef void (* SWIG_Callback7_t)(void *dobj, void *);
    typedef void (* SWIG_Callback8_t)(void *dobj, void *);
    typedef void (* SWIG_Callback9_t)(void *dobj, void *);
    typedef void (* SWIG_Callback10_t)(void *dobj, void *);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackonInit, SWIG_Callback1_t callbackonConnect, SWIG_Callback2_t callbackonDisconnect, SWIG_Callback3_t callbackonExit, SWIG_Callback4_t callbackonFrame, SWIG_Callback5_t callbackonFocusGained, SWIG_Callback6_t callbackonFocusLost, SWIG_Callback7_t callbackonServiceConnect, SWIG_Callback8_t callbackonServiceDisconnect, SWIG_Callback9_t callbackonDeviceChange, SWIG_Callback10_t callbackonImages);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_onInit;
    SWIG_Callback1_t swig_callback_onConnect;
    SWIG_Callback2_t swig_callback_onDisconnect;
    SWIG_Callback3_t swig_callback_onExit;
    SWIG_Callback4_t swig_callback_onFrame;
    SWIG_Callback5_t swig_callback_onFocusGained;
    SWIG_Callback6_t swig_callback_onFocusLost;
    SWIG_Callback7_t swig_callback_onServiceConnect;
    SWIG_Callback8_t swig_callback_onServiceDisconnect;
    SWIG_Callback9_t swig_callback_onDeviceChange;
    SWIG_Callback10_t swig_callback_onImages;
};


#endif
